# Generated by Django 2.2.5 on 2019-10-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('firstName', models.CharField(max_length=90)),
                ('lastName', models.CharField(max_length=90)),
                ('username', models.CharField(max_length=90)),
                ('email', models.CharField(default='', max_length=111)),
                ('address', models.CharField(default='', max_length=111)),
                ('address2', models.CharField(default='', max_length=111)),
                ('country', models.CharField(default='', max_length=111)),
                ('state', models.CharField(default='', max_length=111)),
                ('zip', models.CharField(default='', max_length=111)),
                ('cc_name', models.CharField(default='', max_length=111)),
                ('cc_number', models.CharField(default='', max_length=111)),
                ('cc_expiration', models.CharField(default='', max_length=111)),
                ('cc_cvv', models.CharField(default='', max_length=111)),
            ],
        ),
    ]
