# Generated by Django 2.2.5 on 2019-10-02 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cc_cvv',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cc_expiration',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cc_name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cc_number',
        ),
    ]
