# Generated by Django 2.2.5 on 2019-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address2',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='firstName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='country',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='username',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='zip',
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
